-- ROLE
INSERT INTO ROLE (ROLE_NAME)
VALUES ('ROLE_ADMIN'),
       ('ROLE_USER');

-- USER
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL, USERNAME, PASSWORD, PHOTO_NAME, ACTIVE, ROLE_ID)
VALUES ('admin', 'admin', 'admin@admin.com', 'admin',
        '$2a$10$8UXhGyTthdNY3ayoMeyDb.l5R5iXlekMaWpwtqn87c0ZiA8fRaIqm', 'file-6hnhU31.jpg', true, 1),
       ('Enna', 'McClaren', 'user@user.com', 'user',
        '$2a$10$8UXhGyTthdNY3ayoMeyDb.l5R5iXlekMaWpwtqn87c0ZiA8fRaIqm', 'file-6hnhU30.jpg', true, 2),
       ('Mark', 'Vassel', 'avassel0@chron.com', 'avassel0',
        '$2a$10$8UXhGyTthdNY3ayoMeyDb.l5R5iXlekMaWpwtqn87c0ZiA8fRaIqm', 'file-6hnhU34.jpg', true, 2),
       ('Philis', 'Greenhaugh', 'pgreenhaugh1@earthlink.net', 'pgreenhaugh1',
        '$2a$10$8UXhGyTthdNY3ayoMeyDb.l5R5iXlekMaWpwtqn87c0ZiA8fRaIqm', 'file-6hnhU32.jpg', true, 2),
       ('Natividad', 'Cream', 'ncream2@ox.ac.uk', 'ncream2',
        '$2a$10$8UXhGyTthdNY3ayoMeyDb.l5R5iXlekMaWpwtqn87c0ZiA8fRaIqm', 'file-6hnhU36.jpg', true, 2),
       ('Mariann', 'Gagen', 'mgagen3@desdev.cn', 'mgagen3',
        '$2a$10$8UXhGyTthdNY3ayoMeyDb.l5R5iXlekMaWpwtqn87c0ZiA8fRaIqm', 'file-6hnhU38.jpg', true, 2),
       ('Frants', 'Caudrelier', 'fcaudrelier4@altervista.org', 'fcaudrelier4',
        '$2a$10$8UXhGyTthdNY3ayoMeyDb.l5R5iXlekMaWpwtqn87c0ZiA8fRaIqm', 'file-6hnhU39.jpg', true, 2);

-- TASK
INSERT INTO TASK (title, description, status, priority, created_at, user_id) VALUES
('Chief Design Engineer', 'Spontaneous rupture of flexor tendons, unspecified thigh', 'REQUESTED', 'MEDIUM', '2021-11-11', 4),
('Payment Adjustment Coordinator', 'Nondisp commnt suprcndl fx w/o intrcndl fx r humer, 7thG', 'COMPLETED', 'HIGH', '2021-08-01',  6),
('Programmer I', 'Inj l int carotid, intcr w LOC of unsp duration, sequela', 'IN_PROGRESS', 'MEDIUM', '2021-08-13', 6),
('Web Designer IV', 'Major depressive disorder, recurrent, in remission, unsp', 'IN_PROGRESS', 'LOW', '2021-09-22', 5),
('Human Resources Assistant II', 'Unsp fx shaft of r fibula, 7thN', 'IN_PROGRESS', 'LOW', '2021-10-18', 5),
('GIS Technical Architect', 'Poisoning by unsp drug/meds/biol subst, self-harm, subs', 'COMPLETED', 'LOW', '2021-03-02', 1),
('Librarian', 'Oth fx upr end r rad, subs for opn fx type I/2 w routn heal', 'REQUESTED', 'HIGH', '2021-08-17', 6),
('Software Engineer III', 'Inj great saphenous at lower leg level, right leg, init', 'COMPLETED', 'LOW', '2021-11-04', 3),
('Account Executive', 'Collapsed vertebra, NEC, sacr/sacrocygl region', 'COMPLETED', 'LOW', '2021-11-10', 3),
('Database Administrator IV', 'Other acquired abnormalities of ear ossicles, unsp ear', 'REQUESTED', 'LOW', '2020-12-03',  6),
('Social Worker', 'Accidental twist by another person, initial encounter', 'COMPLETED', 'HIGH', '2021-04-24', 1),
('Internal Auditor', 'Malig neoplasm of upper-inner quadrant of unsp female breast', 'COMPLETED', 'LOW', '2021-01-06', 2),
('Financial Advisor', 'Atheroembolism of unspecified upper extremity', 'IN_PROGRESS', 'LOW', '2021-01-26',  6),
('Engineer II', 'Unsp fracture of right foot, init encntr for closed fracture', 'REQUESTED', 'LOW', '2021-04-03', 5),
('Web Designer I', 'Oth fx shaft of l fibula, 7thN', 'REQUESTED', 'LOW', '2020-12-31', 6),
('Research Assistant I', 'Other specified degenerative diseases of basal ganglia', 'COMPLETED', 'LOW', '2021-09-26', 6),
('Financial Analyst', 'Placentitis, third trimester, fetus 3', 'REQUESTED', 'HIGH', '2021-10-01', 4),
('Sales Associate', 'Abnormal bowel sounds', 'REQUESTED', 'LOW', '2021-04-06', 7),
('Environmental Tech', 'Pathological fracture, left fibula, sequela', 'IN_PROGRESS', 'LOW', '2021-12-30', 2),
('Structural Analysis Engineer', 'Crushing injury of unspecified wrist and hand, subs encntr', 'REQUESTED', 'MEDIUM', '2021-01-07', 7),
('Financial Analyst', 'Displ oblique fx shaft of r fibula, 7thM', 'REQUESTED', 'HIGH', '2021-07-28', 4),
('Automation Specialist III', 'Complete traumatic amputation of right breast, sequela', 'REQUESTED', 'LOW', '2021-07-08', 2),
('Junior Executive', 'Malignant neoplasm of conjunctiva', 'REQUESTED', 'LOW', '2021-12-04',  6),
('Graphic Designer', 'Genetic anomalies of leukocytes', 'COMPLETED', 'HIGH', '2021-08-23', 3),
('Sales Associate', 'Fracture of alveolus of right mandible, 7thB', 'IN_PROGRESS', 'HIGH', '2021-07-04', 4),
('Actuary', 'Activated protein C resistance', 'IN_PROGRESS', 'MEDIUM', '2020-12-07', 6),
('Geologist II', 'Nondisp transverse fx shaft of humerus, unsp arm, sequela', 'COMPLETED', 'LOW', '2021-04-05', 4),
('Operator', 'Corrosion of first degree of unsp shoulder, init encntr', 'IN_PROGRESS', 'HIGH', '2021-09-19', 5),
('Database Administrator III', 'Subluxation of tarsometatarsal joint of unsp foot, sequela', 'REQUESTED', 'LOW', '2021-03-08', 7),
('Paralegal', 'Transient synovitis, hip', 'COMPLETED', 'LOW', '2021-04-02', 4),
('Systems Administrator I', 'Nondisp fx of lateral malleolus of unsp fibula, 7thN', 'REQUESTED', 'HIGH', '2021-10-18', 6),
('Human Resources Assistant IV', 'Disp fx of unsp radial styloid pro, 7thC', 'REQUESTED', 'LOW', '2021-02-01', 6),
('Design Engineer', 'Paralytic calcification and ossification of muscle, shoulder', 'IN_PROGRESS', 'LOW', '2021-10-28', 2),
('Cost Accountant', 'Unsp injury of blood vessels at forarm lv, unsp arm, init', 'IN_PROGRESS', 'HIGH', '2021-06-12', 5),
('Information Systems Manager', 'Impulse disorder, unspecified', 'COMPLETED', 'HIGH', '2021-12-15', 2),
('Chemical Engineer', 'Other fracture of lower end of ulna', 'COMPLETED', 'MEDIUM', '2021-10-29', 2),
('Clinical Specialist', 'Toxic effects of petroleum products', 'COMPLETED', 'LOW', '2021-08-07', 4),
('Account Representative I', 'Toxic effect of harmful algae and algae toxins, undet, sqla', 'COMPLETED', 'LOW', '2021-05-01', 3),
('Help Desk Technician', 'Poisn by pertuss vaccine, inc combin w pertuss, asslt, init', 'REQUESTED', 'HIGH', '2021-04-27',  6),
('Research Assistant I', 'Oth acc to oth private fix-wing aircraft injuring occupant', 'COMPLETED', 'MEDIUM', '2021-08-09',  4),
('Software Test Engineer III', 'Laceration of brachial artery, right side, sequela', 'REQUESTED', 'HIGH', '2021-06-10', 2),
('VP Product Management', 'Delayed and secondary postpartum hemorrhage', 'REQUESTED', 'HIGH', '2021-11-03', 6),
('Teacher', 'Other conditions of integument specific to newborn', 'COMPLETED', 'HIGH', '2021-09-16', 6),
('Chemical Engineer', 'Insect bite (nonvenomous) of left little finger, init encntr', 'COMPLETED', 'HIGH', '2021-09-28', 3),
('Human Resources Manager', 'Passenger in hv veh injured in collision w unsp mv nontraf', 'COMPLETED', 'HIGH', '2021-01-22', 5),
('Teacher', 'Traum rupt of unsp ligmt of l little fngr at MCP/IP jt, init', 'REQUESTED', 'HIGH', '2021-07-05', 1),
('Environmental Tech', 'Other specified injuries of right thigh', 'COMPLETED', 'MEDIUM', '2021-09-18', 6),
('Statistician I', 'Other stimulant dependence, uncomplicated', 'REQUESTED', 'MEDIUM', '2021-02-18', 3),
('Web Designer II', 'Unsp disp fx of fourth cervcal vert, subs for fx w nonunion', 'COMPLETED', 'HIGH', '2021-08-29', 1),
('Editor', 'Unspecified superficial injury of left lower leg', 'COMPLETED', 'LOW', '2021-08-01', 5),
('Human Resources Assistant IV', 'Nondisp spiral fx shaft of unsp fibula, 7thC', 'REQUESTED', 'HIGH', '2021-02-01', 5),
('Executive Secretary', 'Glaucoma secondary to oth eye disord, left eye, mild stage', 'COMPLETED', 'LOW', '2021-02-27', 4),
('Statistician II', 'Assault by other sharp object, subsequent encounter', 'IN_PROGRESS', 'HIGH', '2021-08-27', 1),
('Environmental Specialist', 'Unsp superficial injuries of r bk wl of thorax, sequela', 'COMPLETED', 'HIGH', '2021-02-26', 5),
('Director of Sales', 'Underdosing of other anti-common-cold drugs', 'COMPLETED', 'LOW', '2021-03-24',  4),
('Database Administrator IV', 'Open bite of other specified part of neck, sequela', 'COMPLETED', 'MEDIUM', '2021-03-07',  4),
('Media Manager III', 'Disp fx of pisiform, unsp wrist, subs for fx w nonunion', 'COMPLETED', 'LOW', '2021-01-10', 5),
('Web Designer II', 'Sublux of proximal interphaln joint of l mid finger, sequela', 'COMPLETED', 'LOW', '2021-03-28', 3),
('Geologist I', 'Milt op involving unarmed hand to hand combat, milt, subs', 'COMPLETED', 'HIGH', '2021-07-14', 7),
('Editor', 'Open bite of unspecified upper arm', 'IN_PROGRESS', 'HIGH', '2021-09-05', 2),
('Automation Specialist I', 'Laceration of popliteal vein, right leg', 'COMPLETED', 'LOW', '2021-04-04', 4),
('Quality Control Specialist', 'Lacerat msl/tnd lng extn msl toe at ank/ft lev, l foot, sqla', 'REQUESTED', 'LOW', '2021-10-17', 3),
('Occupational Therapist', 'Displ oblique fx shaft of r femr, 7thE', 'COMPLETED', 'LOW', '2021-05-08', 3),
('Director of Sales', 'Nondisp fx of sternal end r clavicle, subs for fx w malunion', 'COMPLETED', 'LOW', '2021-11-07',  4),
('Senior Editor', 'Strain of extn/abdr musc/fasc/tend of l thm at forarm lv', 'REQUESTED', 'LOW', '2020-12-15', 4),
('Structural Analysis Engineer', 'Puncture wound with foreign body, unsp knee, subs encntr', 'COMPLETED', 'LOW', '2021-04-28', 4),
('Accountant IV', 'Postprocedural hepatic failure', 'REQUESTED', 'LOW', '2021-05-15', 3),
('Professor', 'Traum rupture of unsp ligmt of l rng fngr at MCP/IP jt, subs', 'REQUESTED', 'MEDIUM', '2021-07-20', 3),
('Assistant Media Planner', 'Toxic effect of trichloroethylene, self-harm, sequela', 'REQUESTED', 'HIGH', '2021-03-20', 6),
('Structural Analysis Engineer', 'Dementia in other diseases classified elsewhere', 'REQUESTED', 'LOW', '2021-10-29', 6),
('Sales Associate', 'Early cutaneous congenital syphilis', 'IN_PROGRESS', 'HIGH', '2021-09-11', 4),
('Senior Financial Analyst', 'Lacerat intrinsic musc/fasc/tend thmb at wrs/hnd lv, init', 'COMPLETED', 'LOW', '2021-04-10', 2),
('Human Resources Assistant II', 'Sltr-haris Type III physl fx low end rad, unsp arm, 7thP', 'REQUESTED', 'HIGH', '2021-11-23', 4),
('Community Outreach Specialist', 'Idiopathic chronic gout, left hand, with tophus (tophi)', 'COMPLETED', 'LOW', '2021-08-12', 5),
('Product Engineer', 'Sprain of MCP joint of left ring finger, sequela', 'COMPLETED', 'HIGH', '2021-03-03', 4),
('Senior Cost Accountant', 'Nondisp trimalleol fx r low leg, 7thG', 'REQUESTED', 'LOW', '2021-10-27', 2),
('Registered Nurse', 'Other peripheral vertigo, left ear', 'REQUESTED', 'LOW', '2021-04-16', 4),
('Business Systems Development Analyst', 'Lacerat extn musc/fasc/tend r idx fngr at wrs/hnd lv, subs', 'REQUESTED', 'LOW', '2020-12-20', 3),
('Desktop Support Technician', 'Puncture wound with foreign body of left wrist, sequela', 'COMPLETED', 'LOW', '2020-12-19', 3),
('Food Chemist', 'Asphyxiation due to plastic bag, assault', 'REQUESTED', 'LOW', '2021-05-21', 4),
('Sales Representative', 'Oth injury of deep palmar arch of unspecified hand', 'REQUESTED', 'LOW', '2021-05-17', 7),
('Technical Writer', 'Inj unsp blood vessel at wrs/hnd of right arm, sequela', 'COMPLETED', 'HIGH', '2021-11-07',  4),
('Financial Analyst', 'Pressure ulcer of right upper back, stage 1', 'COMPLETED', 'LOW', '2021-04-13', 3),
('Geologist I', 'Torus fx lower end of right femur, subs for fx w delay heal', 'COMPLETED', 'LOW', '2021-01-09', 2),
('Editor', 'Expsr to oth rapid changes in air pressr during ascent, init', 'REQUESTED', 'LOW', '2021-06-24', 5),
('Recruiting Manager', 'Unspecified injury of pleura, sequela', 'REQUESTED', 'LOW', '2021-09-21', 7),
('Recruiter', 'Nontraumatic compartment syndrome of left lower extremity', 'COMPLETED', 'HIGH', '2021-11-08', 4),
('Paralegal', 'Toxic effect of venom of black widow spider, acc, sequela', 'COMPLETED', 'MEDIUM', '2021-10-30', 7),
('Graphic Designer', 'Corrosion of unspecified degree of nose (septum), sequela', 'COMPLETED', 'HIGH', '2021-01-23', 7),
('VP Marketing', 'Other spondylosis, lumbar region', 'COMPLETED', 'MEDIUM', '2021-10-07', 2),
('Programmer I', 'Unspecified open wound of right wrist, sequela', 'COMPLETED', 'HIGH', '2021-06-11', 1),
('Business Systems Development Analyst', 'Unsp inj great saphenous at lower leg level, unsp leg, subs', 'REQUESTED', 'LOW', '2021-12-03', 5),
('Electrical Engineer', 'Acc pnctr & lac of eye and adnexa during oth procedure', 'IN_PROGRESS', 'HIGH', '2020-12-09', 2),
('Statistician III', 'Other ulcerative colitis with rectal bleeding', 'REQUESTED', 'HIGH', '2021-11-15', 3),
('Product Engineer', 'Crushed by alligator, sequela', 'REQUESTED', 'HIGH', '2021-08-21', 5),
('Paralegal', 'Ped on sktbrd injured in collision w pedl cyc, unsp, init', 'REQUESTED', 'HIGH', '2021-02-22', 2),
('Chemical Engineer', 'Jump/div into swim pool strk surfc causing oth injury, init', 'IN_PROGRESS', 'HIGH', '2021-09-21', 1),
('VP Product Management', 'Nondisplaced Maisonneuve''s fracture of right leg', 'COMPLETED', 'LOW', '2020-12-15', 7),
('Marketing Manager', 'Other subluxation of right radial head, subsequent encounter', 'COMPLETED', 'HIGH', '2021-08-11', 3),
('Analyst Programmer', 'Activity, rappelling', 'COMPLETED', 'LOW', '2020-12-12', 2);
